version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: pontoeletronico-backend
    container_name: pontoeletronico-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - db

  frontend:
    build:
      context: ./admin-frontend
    image: pontoeletronico-frontend
    container_name: pontoeletronico-frontend
    # Não precisa expor porta, será servido pelo nginx

  nginx:
    image: nginx:alpine
    container_name: pontoeletronico-nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./admin-frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    container_name: pontoeletronico-db
    environment:
      POSTGRES_DB: ponto_eletronico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 