FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY backend/pom.xml .

RUN mvn dependency:go-offline

# Copiar JARs do JWT explicitamente
RUN mkdir -p target/dependency && \
    find /root/.m2/repository/io/jsonwebtoken/ -name "*.jar" -exec cp {} target/dependency/ \;

COPY backend/src ./src

RUN mvn package -DskipTests

ENTRYPOINT ["java", "-jar", "target/ponto-eletronico-obra-1.0.0.jar"] 