spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ponto_eletronico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:12345678901234567890123456789012}
  expiration: ${JWT_EXPIRATION:86400000} # 24 horas em milissegundos

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:19006
  geo:
    max-distance: 100 # distância máxima em metros permitida para registro do ponto 