spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ponto_eletronico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:sua_chave_secreta_muito_segura_para_desenvolvimento}
  expiration: 86400000 # 24 horas

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:19006
  geo:
    max-distance: 100 # distância máxima em metros permitida para registro do ponto 